### ISSUE TITLE
AppService-blackbox-tests: some pipeline functions not found in Pipeline.Functions section

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/app-service-configurable#161]
TAF app-service trigger V2 API x86_64 tests is failing from Dec. 22

Updating the ExecutionOrder from Concul, for example,  change default `TransformToXML` to `TransformToJSON`, causes the error :
```
level=ERROR ts=2020-12-23T05:14:54.7467986Z app=AppService-blackbox-tests source=configupdates.go:151 msg="unable to reload Configurable Pipeline from new configuration: function TransformToJSON configuration not found in Pipeline.Functions section"
```
The following is the writable pipeline functions on Consul, and some functions are not listed(e.g. TransformToJSON):
<img width="255" alt="image" src="https://user-images.githubusercontent.com/55377716/102966241-780d1b80-452a-11eb-962f-df9783a0a767.png">

The app-service-blackbos-test in TAF is:
```
  app-service-blackbox-tests:
    image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable:master
    command: "-s -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res"
    ports:
      - 127.0.0.1:48095:48095/tcp
    container_name: app-service-blackbox-tests
    hostname: app-service-blackbox-tests
    environment:
      edgex_profile: blackbox-tests
      Service_Host: app-service-blackbox-tests
      Clients_CoreData_Host: edgex-core-data
      Clients_Logging_Host: edgex-support-logging
      Registry_Host: edgex-core-consul
      Service_Port: 48095
      EDGEX_SECURITY_SECRET_STORE: "false"
    depends_on:
      - consul
      - data
    networks:
      - edgex-network
```
