### ISSUE TITLE
App-metrics-influxdb reports "204 No Content Response" for metrics data exported to InfluxDB 

### ISSUE THREAD

**Issue by M0hanrajp** [edgexfoundry/app-service-configurable#671]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

The issue is located in [metrics-influxdb](https://github.com/edgexfoundry/app-service-configurable/tree/main/res/metrics-influxdb)

The metrics data reported by core-data & device-virtual are recorded in app-metric-influxdb service
& sent via HTTP export but in response get 204 No Content Response.

### Is this a regression?

Not sure on regression testing, I have only executed this on 3.1 Napa docker images.

### Description and Minimal Reproduction [**REQUIRED**]

* Using [compose-builder](https://github.com/edgexfoundry/edgex-compose/tree/main/compose-builder) build a basic docker-compose file consisting of device-virtual, asc-metrics.
* I have included influxDB as a separate service as below:
```yml
  influxdb:
    container_name: edgex-influxdb
    hostname: edgex-influxdb
    environment:
      INFLUXD_LOG_LEVEL: debug
    image: influxdb:latest
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8086
        published: "8086"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - type: volume
        source: influxdb-storage
        target: /var/lib/influxdb2
        volume: {}
```
* HTTP export is working and able to see the data on Influx UI:

![image](https://github.com/user-attachments/assets/c0d4d495-9a02-402e-8f78-d28daa7ff206)

## 🔥 Exception or Error

**Why app-metrics-influxdb reports 204 No Content ? is this expected for metric data ?**

edgex-app-metrics-influxdb logs:
```bash
edgex-app-metrics-influxdb  | level=DEBUG app=app-metrics-influxdb source=http.go:127 msg="HTTP Exporting in pipeline 'default-pipeline'"
edgex-app-metrics-influxdb  | level=DEBUG app=app-metrics-influxdb source=http.go:192 msg="Setting HTTP Header 'authorization' with secret value from SecretStore at secretName='influxdb' & secretKeyValue='token in pipeline 'default-pipeline'"
edgex-app-metrics-influxdb  | level=DEBUG app=app-metrics-influxdb source=http.go:209 msg="POSTing data to http://edgex-influxdb:8086/api/v2/write?org=metrics&bucket=edgex&precision=ns in pipeline 'default-pipeline'"
# "Sent 569 bytes of data in pipeline 'default-pipeline'. Response status is 204 No Content"
edgex-app-metrics-influxdb  | level=DEBUG app=app-metrics-influxdb source=http.go:241 msg="Sent 569 bytes of data in pipeline 'default-pipeline'. Response status is 204 No Content"
edgex-app-metrics-influxdb  | level=TRACE app=app-metrics-influxdb source=http.go:242 msg="Data exported for pipeline 'default-pipeline' (X-Correlation-ID=11b61087-24a8-458c-912b-3f25efc3aeb8)"
```
## 🌍  Your Environment
**Deployment Environment: Ubuntu 22.04.4 LTS**

**EdgeX Version: 3.1 Napa**

---
Thanks
